
#======================================
#======== 听客来系统主配置文件1.0 ======
#======================================

#---------------------------------------------------------------------------------------------------
# 说明：如果需要配置本地开发环境，可以自己创建一个 application-{自定义值}.yml 文件，然后替换这里的环境就行。
#      没有添加版本号说明，另外，如果修改配置文件，需要在下面添加修改记录，修改记录格式参考下面例子。
# 目的：一方面可以加强管理，另一方面可以让不同时期的程序员们进行隔空对话，吐个槽什么的，欢迎来喷!
#
#     团队文化需要建设！如果你感觉可行，就把楼建下去吧！
#
#  @author liuzhengjie
#  @email 869044232@qq.com
#  @date 2018-11-22 14:14:14
#---------------------------------------------------------------------------------------------------

# eg:
#---------------------------------------------------------------------------------------------------
#  配置文件修改说明：
#  目的：添加配置文件修改记录说明,举个栗子而已，后面类同。
#  实现：增添了xxx，修改了xxx，删除了xxx
#  吐槽：楼主太恶心了，改个文件还要写记录！ +1
#  @author liuzhengjie
#  @email 869044232@qq.com
#  @date 2018-11-22 14:23:51
#                                                                                   1楼
#                                                                          赞（10086） 踩（-10086）
#---------------------------------------------------------------------------------------------------

#---------------------------------------------------------------------------------------------------
#  spring-boot小技巧说明：
#
#  目的：记录一些小技巧，防止新手小朋友不知道配置文件怎么玩！
#
#  实现：
#                           配置文件的优先级
# application.properties和application.yml文件可以放在一下四个位置：
#
# 外置，在相对于应用程序运行目录的/congfig子目录里。
# 外置，在应用程序运行的目录里
# 内置，在config包内
# 内置，在Classpath根目录
# 也就是说，src/main/resources/config下application.properties覆盖src/main/resources下application.properties中相同的属性
# 如果你在相同优先级位置同时有application.properties和application.yml，
# 那么application.yml里面的属性就会覆盖application.properties里的属性。
#  吐槽：楼主太恶心了，改个文件还要写记录！ +1！  楼上说的对！
#  @author liuzhengjie
#  @email 869044232@qq.com
#  @date 2018-11-22 14:23:51
#                                                                                   2楼
#                                                                          赞（10086） 踩（-10086）
#---------------------------------------------------------------------------------------------------

# 配置文件设置（幸福4选1）
# 目前有4种环境配置，dev：开发环境，test：测试环境，beta：内测环境，prod：正式环境
spring:
  profiles:
    active: dev